version: '3.8'

services:
  postgres:
    image: "postgres"


  f1-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SSH_AUTH_DOCK=/ssh-age
    volumes:
      - .:/app
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

  wroom:
    build:
      context: ./services/wroom
      dockerfile: Dockerfile-dev
#    volumes:
#      - ./services/wroom:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
