version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^' 
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.yml run wroom python manage.py test
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar