version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^' 
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.yml run wroom python manage.py test