# base image
FROM python:3.9
# set working directory
WORKDIR /usr/src/app
ENV PYTHONPATH=/usr/src/app

RUN apt-get -y update
RUN apt-get -y install git

RUN apt-get -y install postgresql && \
    apt-get -y install netcat-openbsd && \
    apt-get -y install manpages-dev && \
    apt-get -y install libpq-dev

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
# add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh
# add app
COPY . /usr/src/app
# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]